name: kasir
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4 
  intl: ^0.18.0
  pdf: ^3.10.4
  printing: ^5.11.1
  url_launcher: ^6.2.1
  print_bluetooth_thermal: ^1.1.8
  esc_pos_utils_plus: ^2.0.3
  image: ^4.1.4
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.1 
  mobile_scanner: ^5.2.3
  fl_chart: ^0.68.0 
  share_plus: ^10.0.0
  barcode_scan2: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9 

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/logo_loading.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png" # Sesuaikan dengan nama file logo Anda di assets
  adaptive_icon_background: "#2D68F8" # Warna latar belakang biru sesuai tema aplikasi
  adaptive_icon_foreground: "assets/ic_launcher.png"

flutter_native_splash:
  color: "#448AFF"               # Warna background biru (sama dengan blueAccent)
  image: "assets/logo_loading.png" # Path logo loading Anda
  android_12:
    color: "#448AFF"
    image: "assets/logo_loading.png"
  fullscreen: true               # Supaya tampil penuh satu layar
