name: kasir
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4 
  intl: ^0.18.0
  pdf: ^3.10.4
  printing: ^5.11.1
  url_launcher: ^6.2.1
  print_bluetooth_thermal: ^1.1.8
  esc_pos_utils_plus: ^2.0.3
  image: ^4.1.4
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.1 
  mobile_scanner: ^5.2.3
  fl_chart: ^0.68.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
